### PR TITLE
Add error message styling

### PR DESCRIPTION
**Pull request by KevSlashNull**
This fixes the error message types (following #147) and improves their styling, so error messages stand out more and are visibly errors.

cc @xhayper 

## Screenshots

| Theme | Before | After |
| --- | --- | --- |
| Light | image | image |
| Dark | image | image |

### CODE REVIEW

**Comment by xhayper** [comment]
Looks great! don't forget about the main page where you have to login though. 

`app.vue`

**Comment by KevSlashNull** [comment]
@xhayper good call! i’ll take that in a follow up, so i can make the login site a bit more beautiful by e.g. adding the logo and showing an error if you don’t have access.

**Comment by xhayper** [comment]
Good idea! if possible, could there be a bypass for the login page so i can help out with the admin site? i understand if you don't want to, everything else LGTM!

**Review by xhayper — APPROVED** [review]

**Review by strideynet — APPROVED** [review]
LGTM - As a seperate thing, I do think we should look into Tanstack Query again so we can make sure we're forced to handle errors where they happen.

**Comment by KevSlashNull** [comment]
@strideynet, yeah for sure! Some errors are also still unhandled, like queue actions, which would be easier with TanStack Query. I’ve had it on my todo list for a while now but now there also is https://github.com/strideynet/bsky-furry-feed/issues/154.

**Pull request merged**
